README reworked
TheAssassin/AppImageLauncher pull request #363
Opened 2020-10-06 22:17 UTC by comradekingu

2020-10-06 22:19 UTC, comradekingu commented on README.md
> +It scans a predefined set of directories including `~/Downloads` and `~/.bin`, makes AppImages which are found executable and performs the desktop integration. This is rather inefficient, as appimage
> It scans a predefined set of directories including `~/Downloads` and `~/.bin`, makes AppImages which are found executable

?

2020-10-06 22:20 UTC, comradekingu commented on README.md
> +    - contains a few wrong assumptions: as soon as AppImageLauncher is installed, you do not have to make AppImages executable, you can just double-click them (or otherwise open them, e.g., from your
web-browser "Downloads", or clickable list of downloads?

2020-10-06 22:21 UTC, comradekingu commented on README.md
> +AppImageLauncher is a new solution that integrates deeply in the system and intercepts all attempts to open an AppImage, becoming the first instance to handle all AppImage invocations.
This section could be cut, as it is arguable replicated above. It is OK for people writing articles.

2020-10-07 23:59 UTC, TheAssassin requested changes
Thanks for helping out. I've got a few proposals and change requests.

2020-10-07 23:59 UTC, TheAssassin commented on README.md
> +AppImageLauncher is a new solution that integrates deeply in the system and intercepts all attempts to open an AppImage, becoming the first instance to handle all AppImage invocations.
I'd rather keep it this paragraph, but would split the sentence in half:

```suggestion
AppImageLauncher is a new solution that integrates deeply in the system.
It intercepts all attempts to open an AppImage, [...]
```

The second sentence should end in something like "takes responsiblity for the AppImage process", "handles them during their lifetime" etc. That'd also allow to dump the following sentence.

2020-10-07 23:59 UTC, TheAssassin commented on README.md
> +It can perform the desktop integration, AppImage removal (also called "uninstallation" sometimes, but as AppImages are not really installed, this term doesn't fit very well), and could be used for ma
Updating is actually available now. The sentence needs an update.

2020-10-07 23:59 UTC, TheAssassin commented on README.md
> +English
I would like to keep them in the order how I discovered them. Also, the title "English" makes little sense, as the other languages are not mentioned. Let's keep the suffixes.

2020-10-07 23:59 UTC, TheAssassin commented on README.md
> +  - please note that AppImageLauncher could *not* be "installed" via AppImage at that time, only recently we added a Lite version that now can be installed from an AppImage (more information will fol
It's a comment for this specific article. Removing the indentation is not a good idea.

2020-10-07 23:59 UTC, TheAssassin commented on README.md
> +
See above. This makes no sense.

2020-10-07 23:59 UTC, TheAssassin commented on README.md
> +    - contains a few wrong assumptions: as soon as AppImageLauncher is installed, you do not have to make AppImages executable, you can just double-click them (or otherwise open them, e.g., from your
Whatever UI the web browser offers to the user to directly open files they downloaded. IMO this is quite clear from the existing text.

2020-10-07 23:59 UTC, TheAssassin commented on README.md
> +AppImageLauncher integrates deeply into the systems. Therefore, an installation via native system packages is the preferred way to install AppImageLauncher. This way, AppImageLauncher's package can p
The plural in "systems" makes no sense.

```suggestion
AppImageLauncher integrates deeply into the system. Therefore, an installation via native system packages is the preferred way to install AppImageLauncher. This way, AppImageLauncher's package can perform the necessary steps to have your system use it for all AppImage invocations.
```

2020-10-07 23:59 UTC, TheAssassin commented on README.md
> +Compatibility table (likely incomplete, feel free to send PRs to add distributions)
Why would you remove "please"? Being polite here is not a mistake IMO.

2020-10-07 23:59 UTC, TheAssassin commented on README.md
> +| `appimagelauncher-<version>.xenial_(amd64,i386).deb` | Ubuntu Xenial | Ubuntu Xenial (16.04), Debian Stretch (9), Netrunner 17.01 |
In my view, all the distros actually prefer to have these codenames be lower case. What's your reason to change the casing?

2020-10-07 23:59 UTC, TheAssassin commented on README.md
> +**Note:** If your system is not listed above as supported, feel free to request support in an issue to discuss adding support.
Same as above. Also, the now combined sentence contains the word "support" twice. Either restore the old form (and improve the wording this way), or shorten it even further:

```suggestion
**Note:** If your system is not listed above as supported, please feel free to open an issue to discuss adding support.
```

2020-10-07 23:59 UTC, TheAssassin commented on README.md
> +When the user launches an AppImage, the software checks whether the AppImage has been integrated already.
These last two sections really need an update...

2020-10-08 04:00 UTC, comradekingu commented on README.md
> +When the user launches an AppImage, the software checks whether the AppImage has been integrated already.
```suggestion
When the user launches an AppImage, the software checks whether it has been integrated already.
```

2020-10-08 04:08 UTC, comradekingu commented on README.md
> +Compatibility table (likely incomplete, feel free to send PRs to add distributions)
Pleonasm? It already says "feel free", which is an addition to "send PRs to __".

2020-10-08 04:09 UTC, comradekingu commented on README.md
> +| `appimagelauncher-<version>.xenial_(amd64,i386).deb` | Ubuntu Xenial | Ubuntu Xenial (16.04), Debian Stretch (9), Netrunner 17.01 |
Ubuntu doesn't, Debian does a bit of both. This doesn't reference the package repos.

2020-10-08 04:19 UTC, comradekingu commented on README.md
> +**Note:** If your system is not listed above as supported, feel free to request support in an issue to discuss adding support.
```suggestion
**Note:** Open an issue if you want to have something added to the list of supported systems above.
```

2020-10-08 04:20 UTC, comradekingu commented on README.md
> +Compatibility table (likely incomplete, feel free to send PRs to add distributions)
```suggestion
Compatibility table (likely incomplete, feel free to send PRs to add distributions).
```

2020-10-08 04:47 UTC, TheAssassin commented on README.md
> +Compatibility table (likely incomplete, feel free to send PRs to add distributions)
"Feel free" is more like "just" an offer. "Please" expresses that readers are really encouraged to create PRs. It's not a pleonasm of any kind.

2020-10-08 04:51 UTC, TheAssassin commented on README.md
> +**Note:** If your system is not listed above as supported, feel free to request support in an issue to discuss adding support.
Hmmm... This sentence kind of promises that any request will be implemented. That might be a bit "too much". "Something" is also a pretty dull wording.

```suggestion
**Note:** Please feel free to request support for additional distributions by [opening an issue](https://github.com/TheAssassin/AppImageLauncher/issues/new).
```

2020-10-08 18:04 UTC, comradekingu commented on README.md
> +Installation makes your Linux desktop AppImage ready™, and you can double-click AppImages again without making them executable first.
I don't like the advertisement angle. It is still there, and it doesn't do anything.

2020-10-08 18:10 UTC, comradekingu commented on README.md
> +Updating and removing AppImages can also be done from there.
Changed the whole thing around.

2020-10-08 18:14 UTC, comradekingu commented on README.md
> +The average user doesn't necessarily like a Downloads directory full of AppImages with cryptic filenames.
I like it, because it points out clearly what otherwise would be the case, and makes a point out of how this is a thing for regular users.

2020-10-08 18:17 UTC, comradekingu commented on README.md
> +AppImageLauncher is a new solution that integrates deeply in the system and intercepts all attempts to open an AppImage, becoming the first instance to handle all AppImage invocations.
"integrates deeply in the system" sounds quite bad, and it would be "into". Going "with".

2020-10-08 18:22 UTC, comradekingu commented on README.md
> +Compatibility table (likely incomplete, feel free to send PRs to add distributions)
The please qualifies the feel free though. Sould be comma otherwise (?)

2020-10-08 18:32 UTC, comradekingu commented
@TheAssassin I think that is good to go(?)
Might have missed something, but by and large I think it does what it should.

2020-10-08 19:05 UTC, TheAssassin commented on README.md
> +Installation makes your Linux desktop AppImage ready™, and you can double-click AppImages again without making them executable first.
This sentence was quoted in many articles. It may be advertising, but what's wrong with that?

2020-10-08 19:09 UTC, TheAssassin commented on README.md
> +Integrate AppImages to your application launcher with one click, wherefrom you can manage, update and remove them.
Wherefrom is really archaic, and doesn't work well in a tech context.

2020-10-08 19:09 UTC, comradekingu commented on README.md
> +Installation makes your Linux desktop AppImage ready™, and you can double-click AppImages again without making them executable first.
Reduced rank for any new articles. The main problem is it doesn't carry anything.
Use it somewhere and in some manner that signifies it is a slogan.
Go all the way with a nice SVG or something.

2020-10-08 19:12 UTC, TheAssassin commented on README.md
> +AppImageLauncher is a new solution that integrates deeply in the system and intercepts all attempts to open an AppImage, becoming the first instance to handle all AppImage invocations.
To invoke, to execute, to run, they're all pretty much synonyms in this context.

2020-10-08 19:30 UTC, comradekingu commented on README.md
> +Integrate AppImages to your application launcher with one click, wherefrom you can manage, update and remove them.
How is it any different from "furthermore"?

2020-10-08 20:19 UTC, TheAssassin commented on README.md
> +Installation makes your Linux desktop AppImage ready™, and you can double-click AppImages again without making them executable first.
> Go all the way with a nice SVG or something. Presumably you don't hold a trademark for it?

I don't have to? It's also not meant too seriously.

I don't understand this "either you don't use it at all or you must design some sort of SVG". It makes no sense to me. Let's keep it as is.

2020-10-08 20:21 UTC, TheAssassin commented on README.md
> +Integrate AppImages to your application launcher with one click, wherefrom you can manage, update and remove them.
Furthermore is not an archaic term as far as I can see, it's modern English. And it's not a synonym for "wherefrom".

Will combine your suggestions with my own change requests, create some sort of result and push it tonight.

2020-10-08 20:47 UTC, comradekingu commented on README.md
> +Installation makes your Linux desktop AppImage ready™, and you can double-click AppImages again without making them executable first.
The point is to not be cheap with it. To make that concern count, everything has to be in order, and it has to be done right. Otherwise it ages quick.

2020-10-08 21:10 UTC, TheAssassin commented on README.md
> +Installation makes your Linux desktop AppImage ready™, and you can double-click AppImages again without making them executable first.
I don't understand what you mean.

2020-10-08 22:09 UTC, comradekingu commented on README.md
> +Integrate AppImages to your application launcher with one click, wherefrom you can manage, update and remove them.
```suggestion
Integrate AppImages to your application launcher with one click, and manage, update and remove them from there.
```

2020-10-08 22:12 UTC, comradekingu commented on README.md
> +    - contains a few wrong assumptions: as soon as AppImageLauncher is installed, you do not have to make AppImages executable, you can just double-click them (or otherwise open them, e.g., from your
Quite is not what I'm going for. We need simple.

2020-10-08 22:14 UTC, comradekingu commented on README.md
> +When the user launches an AppImage, the software checks whether the AppImage has been integrated already.
I put them at the beginning before I saw the comment, so I agree wholeheartedly.

2020-10-08 22:15 UTC, comradekingu commented on README.md
> +Integrate AppImages to your application launcher with one click, wherefrom you can manage, update and remove them.
No don't do that, let's keep it within reason of a snimple snuppler like myself.

2020-11-08 00:50 UTC, TheAssassin commented
Thanks a lot for your efforts. I've fixed a few sections (which you might have misunderstood), and corrected a few minor flaws. Overall, this PR is a great improvement, making the README a lot more readable.

I've updated your branch and will merge it once the CI is happy about it.

2020-11-08 17:33 UTC, merged