Feature/improve desktop integration dialog
TheAssassin/AppImageLauncher pull request #400
Opened 2021-02-12 03:16 UTC by azubieta

Replace the inline "Desktop Integration" dialog with a class. This will allow us to customize the dialog in the future.

2021-02-12 03:18 UTC, azubieta commented
This is the first PR of many, the main focus will be to improve the integration dialog, please review.

2021-02-20 06:26 UTC, vadi2 commented
Any updates?

2021-03-25 03:10 UTC, TheAssassin requested changes
Sorry it took so long, but I only got to having a look at your PR now. I like the change overall, but found a few things I'd like to be changed, mostly minor stuff.

I'd highly appreciate an example screenshot in UI-related PRs by the way. I also try to always provide screenshots in projects I contribute to.

2021-03-25 03:10 UTC, TheAssassin commented on src/ui/integration_dialog.cpp
> +    this->done(Options::INTEGRATE_AND_RUN);
I'm slightly confused, but I suppose that you're (ab)using the fact that `QDialog::Rejected` is a numeric value, and any value other than it means the dialog was `Accepted`?

I have to admit that I don't like this. It's using some implicit behavior from Qt that isn't documented. The Qt 5 docs only mention the values 0 and 1, and nothing else.
I also consider the lack of documentary comments for this problematic. I only really understood it because I recently wrote some `QDialog` based UI myself. Your intent wasn't anything close to obvious.

How about defining a custom result member var, exposing it via a getter, and just using `Accepted` and `Rejected`?

I imagine something like

```cpp
enum ResultingAction {
    DoNothing,
    IntegrateAndRun,
    RunOnce
}

/* ... */

    this->setResultingAction(IntegrateAndRun);
    this->accept();
```

Sure, it's a little bit more laborious, but it doesn't depend on undefined behavior. Also, I figure it's easier to understand. But, really, some comments that explain your intents would be welcome.

2021-03-26 00:14 UTC, azubieta commented on src/ui/integration_dialog.cpp
> +    explanationStrm << QObject::tr("Integrating it will move the AppImage into a predefined location, "
I tried to make the as few changes as possible in order to move away the integration dialog logic from main.

2021-03-26 00:43 UTC, azubieta commented on src/ui/integration_dialog.cpp
> +    this->done(Options::INTEGRATE_AND_RUN);
From my point of view QDialog includes the Accept or Reject to simplify its use in certain scenarios and left the possibility of passing a custom value to the done method for more advanced use cases (otherwise the would have used a boolean value).

Following that logic I extended (to avoid collisions with any internal logic) the basic values and reused the notification method that the QDialog already uses.

Notice that this is not the final version of the changes I want to make. Actually it's just the first step to split the UI from the logic.

2021-03-26 22:29 UTC, azubieta commented on src/ui/main.cpp
> +    integrationDialog->show();
Do you mean using the exec  method from the QDialog or from QApplication ?

2021-03-26 22:34 UTC, azubieta commented on src/ui/integration_dialog.cpp
> +    this->pathToAppImage = std::move(pathToAppImage);
Seems fair, done!

2021-03-26 22:38 UTC, azubieta commented on src/ui/integration_dialog.cpp
> +    QIcon icon = style()->standardIcon(QStyle::SP_MessageBoxQuestion);
I would like to place the application icon here but having the AppImageLauncher one as fallback seems fair.

2021-03-26 22:39 UTC, azubieta commented on src/ui/integration_dialog.cpp
> +    QIcon icon = style()->standardIcon(QStyle::SP_MessageBoxQuestion);
Done

2021-03-26 22:54 UTC, TheAssassin commented on src/ui/main.cpp
> +    integrationDialog->show();
https://doc.qt.io/qt-5/qdialog.html#exec

2021-03-26 22:54 UTC, TheAssassin commented on src/ui/integration_dialog.cpp
> +    explanationStrm << QObject::tr("Integrating it will move the AppImage into a predefined location, "
I see. Let's create an issue for it. I think it's worth doing this at some point.

2021-03-26 22:54 UTC, TheAssassin commented on src/ui/integration_dialog.cpp
> +    QIcon icon = style()->standardIcon(QStyle::SP_MessageBoxQuestion);
Sure, it's just a temporary solution, but a lot better than a big question mark.

2021-03-26 22:56 UTC, TheAssassin commented on src/ui/integration_dialog.cpp
> +    this->done(Options::INTEGRATE_AND_RUN);
I'm pretty sure `Accepted` and `Rejected` are more readable than a boolean. 2-value enums aren't that rare.

Do you have a link to some resource that confirm your assumptions?

2021-03-26 22:56 UTC, TheAssassin commented
Your screenshot looks pretty good, although the window should probably expand vertically, like the old dialog did.

2021-03-26 23:09 UTC, azubieta commented on src/ui/main.cpp
> +    integrationDialog->show();
It's better to use the main application event loop otherwise when the dialog exit the application will be terminated and some events may not be processed.

Check the note in the doc: 
```
Note: Avoid using this function; instead, use open(). Unlike exec(), open() is asynchronous, and does not spin an additional event loop. This prevents a series of dangerous bugs from happening (e.g. deleting the dialog's parent while the dialog is open via exec()). When using open() you can connect to the finished() signal of QDialog to be notified when the dialog is closed.
```

2021-03-26 23:11 UTC, azubieta commented on src/ui/integration_dialog.cpp
> +    explanationStrm << QObject::tr("Integrating it will move the AppImage into a predefined location, "
I used a parametrized string which is stored in the UI file and updated here:

https://github.com/TheAssassin/AppImageLauncher/pull/400/files#diff-d3dbd9afd379767626245e4a245bb1e76032ad9a99a60f67931968b836befd5eR30

2021-03-26 23:20 UTC, azubieta commented on src/ui/integration_dialog.cpp
> +    this->done(Options::INTEGRATE_AND_RUN);
Sadly the documentation doesn't make any recommendations about this. In the stackoverflow they recommend to use signals and slots instead.

2021-03-26 23:25 UTC, azubieta commented on src/ui/integration_dialog.cpp
> +    this->done(Options::INTEGRATE_AND_RUN);
About your fear of breaking something, with passing custom values into the done function. The doc says nothing about whether is it safe or not :(

So let's take the safe path, make another var.

2021-03-26 23:51 UTC, TheAssassin commented on src/ui/main.cpp
> +    integrationDialog->show();
I see. I wasn't aware that `QApplication::exec()` differs like that. Thanks for the hint.

2021-03-27 00:03 UTC, TheAssassin commented on src/ui/integration_dialog.cpp
> +    this->done(Options::INTEGRATE_AND_RUN);
Confirms what I estimated, too. But in the current state, using slots/signals wouldn't make a lot of sense at this point. I'd say, let's built a temp solution like a separate var. Can always be rewritten.

2021-03-27 00:05 UTC, azubieta commented on src/ui/integration_dialog.cpp
> +    this->done(Options::INTEGRATE_AND_RUN);
Done

2021-03-29 19:31 UTC, TheAssassin commented on src/ui/main.cpp
> +    integrationDialog->exec();
Now I'm curious: why are you calling the dialog's `exec()` now? I'm pretty sure you used to call `QApplication::exec()`.

2021-03-29 22:12 UTC, azubieta commented on src/ui/main.cpp
> +    integrationDialog->exec();
In this scenario the QDialog is the only window and the only part of the code that relies on the QEventsLoop. Which meas that once the dialog exits we will not required the events loop enymore.

The [QDialog::exec method](https://doc.qt.io/qt-5/qdialog.html#exec) starts an evenstloop for its sole use, therefore is a good fit. We would have to use the QAppliaction::exec if there were other events (signals/slots) to be processed after the dialog is closed.

2021-03-29 22:24 UTC, TheAssassin commented on src/ui/main.cpp
> +    integrationDialog->exec();
Exactly what I was thinking, too. Thanks for clarifying. We can always fix/improve if we get rid of the solely synchronous workflow (although I'm sure there's higher priorities).

2021-03-29 22:26 UTC, merged

2021-03-29 22:26 UTC, TheAssassin commented
Thanks again!